### ISSUE TITLE
Issues with definition of the 'category' attribute

### ISSUE THREAD

**Issue by michzimny** [smart-data-models/dataModel.Device#11]
These are my comments from #9 that was closed, as I cannot reopen it.

1. In [DeviceModel/doc/spec.md](https://github.com/smart-data-models/dataModel.Device/blob/master/DeviceModel/doc/spec.md), `category` is not defined.
2. In [Device/doc/spec.md](https://github.com/smart-data-models/dataModel.Device/blob/master/Device/doc/spec.md), `category` is bad formatted.

Re 1:
It was well described before the changes in December 2020:

> -   `category` : Device's category(ies).
    -   Attribute type: Property. List of [Text](https://schema.org/Text)
    -   Allowed values, one of the following or any other meaningful to the
        application:
    -   `sensor` : A device that detects and responds to events or changes in
        the physical environment such as light, motion, or temperature changes.
        [https://w3id.org/saref#Sensor](https://w3id.org/saref#Sensor).
    -   `actuator` : A device responsible for moving or controlling a mechanism
        or system. [https://w3id.org/saref#Actuator](https://w3id.org/saref#Actuator).
    - (...)

Re2 :

The current state:

> - `category`: A device that detects and responds to events or changes in the physical environment such as light, motion, or temperature changes. https://w3id.org/saref#Sensor. actuator : A device responsible for moving or controlling a mechanism or system. https://w3id.org/saref#Actuator. Meter : A device built to accurately detect and display a quantity in a form readable by a human being. Partially defined by SAREF. HVAC : Heating, Ventilation and Air Conditioning (HVAC) device that provides indoor environmental comfort. https://w3id.org/saref#HVAC. Network : A device used to connect other devices in a network, such as hub, switch or router in a LAN or Sensor network. (https://w3id.org/saref#Network.Multimedia : A device designed to display, store, record or play multimedia content such as audio, images, animation, video. Enum:'actuator, beacon, endgun, HVAC, implement, irrSection, irrSystem, meter, multimedia, network, sensor'  

For instance, it is not clear what is the first part about ("A device that detects..."). Perhaps, word "sensor" is missing in the beginning. Attribute type is missing. It says 'Meter', but the correct value is 'meter'. A parenthesis is open but not closed. etc.

Forgive me but the problem is that we were referring to this documentation in our project, and since those changes, it's harder to read and to understand by newcomers.

**Comment by albertoabellagarcia** [comment]
You were absolutely  right, there were a couple of issues with the data models, now there are CR on the spec and category is also present on the DeviceModel data model. 
Please make a PR con the CONTRIBUTORS.yaml file to include you. 
Best
