### ISSUE TITLE
Device schema cannot be used in Javascipt / Python since those Regex engines do not support POSIX Bracket Expressions

### ISSUE THREAD

**Issue by christian-knecht** [smart-data-models/dataModel.Device#22]
I cannot use the Device schema in my express-openapi project since macAddress pattern ^([[:xdigit:]]{2}[:.-]?){5}[[:xdigit:]]{2}$ is not supported by the Javascript Regex engine.

Could you please replace the POSIX Bracket Expression [[:xdigit:]] for hexadecimal digits through [A-Fa-f0-9] which is supported by all engines?

**Comment by albertoabellagarcia** [comment]
You were right.
From my point of view this one (with additional parenthesis) and removed the extra character is more correct/complete
^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$

I guess that the extra character between elements of the mac address '?' (potentially a space) is somehow incorrect to get accepted. So I have removed it as well.
Thanks a lot.
