### ISSUE TITLE
Questions/Extensions to the Camera Data Model

### ISSUE THREAD

**Issue by jpnbastos** [smart-data-models/dataModel.Device#25]
We are in the process of adding our information of the CCTV in the are of our municipality and a few questions arose during the data model transformation (from our old data model to the Camera data model):

1) We have a status field that indicates if the camera is in operation, with issues, repairing, disable, etc. There seems to be no corresponding field. Would it be possible to add this field to the data model. The use-case for us is to understand and only display working camera's.
2) Is there an update on the cameraType enumerator? Is it still the 3 fields? We would like to add-one for Traffic Cameras.

Thank you in advance, if you agree with them I would be more than happy to contribute these changes!

**Comment by albertoabellagarcia** [comment]
For the on off there is a on property at this data model [https://github.com/smart-data-models/dataModel.RoboticIndustrialActivities/tree/master/VacuumPump](https://github.com/smart-data-models/dataModel.RoboticIndustrialActivities/tree/master/VacuumPump) I guess is quite the same. then copy it in a PR. 

Regarding the enumeration of types, certainly it can be extended.
for both contributions, we need a payload of examples.
