### ISSUE TITLE
Device: Non NGSI-LD conform example for controlledAsset

### ISSUE THREAD

**Issue by Blobonat** [smart-data-models/dataModel.Device#28]
The [example](https://github.com/smart-data-models/dataModel.Device/blob/master/Device/examples/example-normalized.jsonld) for `controlledAsset` of a `Device` right now is 
```
"controlledAsset": {
        "type": "Relationship",
        "object": [
            "urn:ngsi-ld::wastecontainer-Osuna-100"
        ]
}
```
This usage of a list of Relationships is non conform to the current NGSI-LD specification (similar to the previous normalized NGSI-LD examples of the [Road Data Model](https://github.com/smart-data-models/dataModel.Transportation/issues/16)). Instead the example should look like this:
```
"controlledAsset": [
      {
        "type": "Relationship",
        "object":  "urn:ngsi-ld::wastecontainer-Osuna-100"
      }       
]
```
The  `datasetId` can be omitted here, because there is only 1 (default) item. According to the current specification:
> If no datasetId is provided, it is considered as the default Attribute instance. Thus the creation, updating, appending or deleting of Attributes without providing a datasetId only affects the default Attribute instance.

I am not sure whether
```
"controlledAsset": 
      {
        "type": "Relationship",
        "object":  "urn:ngsi-ld::wastecontainer-Osuna-100"
      }       
```
would also be valid in this case.

---

Additionally I saw that `schema.json` uses a `Property` annotation/description for `controlledAsset`:
```
"controlledAsset": {
          "type": "array",
          "description": "Property. Model:'https://schema.org/Text'. List of the asset(s) (building, object, etc.) controlled by the device.",
...
```
Shouldn't this be a `Relationship`?

**Comment by Blobonat** [comment]
Additionally I saw that `schema.json` uses a `Property` annotation/description for `controlledAsset`:
```
"controlledAsset": {
          "type": "array",
          "description": "Property. Model:'https://schema.org/Text'. List of the asset(s) (building, object, etc.) controlled by the device.",
...
```
Shouldn't this be a `Relationship`?

**Comment by albertoabellagarcia** [comment]
You are right about the example (fisxed)

Regarding the schema this is the current version on the schema
 "controlledAsset": {
          "type": "array",
          "description": "Property. Model:'https://schema.org/Text'. List of the asset(s) (building, object, etc.) controlled by the device.",
          "items": {
            "oneOf": [
              {
                "type": "string",
                "format": "uri"
              },
              {
                "$ref": "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/EntityIdentifierType"
              }
            ]
          }
        },

As you can see the items can be either a property or a relationship, so property has been chosen for the array. Why? No actual reason as far as I know. One has to be chosen.
