### ISSUE TITLE
Device examples do not include configuration property

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/dataModel.Device#30]
The different examples related to the schema Device do not include an example of the content of configuration property. See for example [example.jsonld](https://github.com/smart-data-models/dataModel.Device/blob/master/Device/examples/example.jsonld)

**Comment by albertoabellagarcia** [comment]
True, not always the examples cover all attributes. Although it is encouraged they are not always available. Glad to receive actual examples if available.
