### ISSUE TITLE
Parent-child relationship

### ISSUE THREAD

**Issue by Thue77** [smart-data-models/dataModel.Device#31]
This is not so much an issue, as a question, so please redirect me if there are more appropriate places to ask this.

How can a child-parent relationship between devices be modelled? Is the model still being followed even if a new attribute _refParentDevice_ is added to give the relationship or can this be dealt with in a different manner within, the scope of the model?

**Comment by albertoabellagarcia** [comment]
Certainly it can be included as long as you provide real examples showing it working. The contribution manual is here [https://bit.ly/contribution_manual](https://bit.ly/contribution_manual)  
In order to do that just create a PR in this repository.
