### ISSUE TITLE
Schema Error

### ISSUE THREAD

**Issue by Neeraj-Nec** [smart-data-models/dataModel.Device#32]
In the Device schema (https://github.com/smart-data-models/dataModel.Device/blob/master/Device/schema.json), the `controlledProperty` attribute is listed as a required field but lacks defined type and other properties. This needs to be corrected to ensure the schema is complete and functional.

The relevant part of the schema:

{
  "required": [
    "id",
    "type",
    "controlledProperty"
  ]
}
Regards 
Neeraj Srivastava

**Comment by albertoabellagarcia** [comment]
We have checked the schema and there were tiny errors but not affecting what you mean and already fixed. 
[here the test](https://smartdatamodels.org/index.php/test-results/?datamodelRepoUrl=https%3A%2F%2Fgithub.com%2Fsmart-data-models%2FdataModel.Device%2Ftree%2Fmaster%2FDevice&email=alberto.abella%40fiware.org&testnumber=0&yamlOutput=0
) 

On the other hand, the attribute "controlledProperty" is inserted in the schema in line  17 thanks to this reference to  "https://smart-data-models.github.io/dataModel.Device/device-schema.json#/definitions/Device-Commons" 
 so maybe this hide you from seeing in the schema. 
Please reopen this issue if we have not answer your point.
