### ISSUE TITLE
rssi property should be expressed as dBm or renamed to be Normalized rssi

### ISSUE THREAD

**Issue by franckLG** [smart-data-models/dataModel.Device#4]
The rssi property is defined as follow "rssi : Received signal strength indicator for a wireless enabled device. It must be equal to 1.0 when the signal strength is maximum. 0.0 when signal is missing. -1.0 when it cannot be determined."

However, signal strength is usually expressed in mW or dBm. For example, a LoRaWAN device can have sensitivity below -120dBm and thus receive signals which could have rssi of -125dBm.
The current [0-1] scale looks like a "normalized rssi" which is not always available (which system provide such a normalised value ? Mobile handsets ?) 

=> I suggest to modify the allowed range or clearly differentiate absolute vs normalised rssi.

**Comment by albertoabellagarcia** [comment]
Let's discuss definitely with users, but if this is not the current use in real case scenario, it will be changed.

**Comment by albertoabellagarcia** [comment]
Now we are in discussion with the contributors, youi'll receive a mail.

**Comment by albertoabellagarcia** [comment]
After a while without any complain, it's documented in the  [wiki](https://github.com/smart-data-models/dataModel.Device/wiki) the change to the Franck's proposed option.
