### ISSUE TITLE
Several quantitative values with different time stamps

### ISSUE THREAD

**Issue by LEiAl** [smart-data-models/dataModel.Device#5]
We have a use case where we have devices with several quantitative values AND different time stamps. We cannot map this use case with the device model (also attached):
"controlledProperty": ["fillingLevel", "temperature"],
 "value": "l%3D0.22%3Bt%3D21.2",

I could have thought of two possible solutions:
1: an additional timestamp per measured value; e.g. like:
{
	"controlledProperty": ["electric_power"],
	"value_electric_power": 5.00,
	"timestamp_electric_power": "2020-06-01T00:00:00.00Z",

	"controlledProperty_1": ["temperature"],
	"value_temperature": 21.00,
	"timestamp_temperature": "2020-06-01T00:10:00.00Z"
}

2: an additional/ new model "device observation" 

![device_conrtolledProperty](https://user-images.githubusercontent.com/61869104/85689038-95c00c00-b6d2-11ea-89ed-7d202fd38138.jpg)
![device_value](https://user-images.githubusercontent.com/61869104/85689040-95c00c00-b6d2-11ea-8ad2-8560b02bd3b5.jpg)

Thanks and regards, Aline

**Comment by albertoabellagarcia** [comment]
You are right you cannot manage this multisensor with the device data model, that's why we are creating a new one. 
We are drafting it [here](https://github.com/smart-data-models/pending/blob/master/Node/schema.json) but it is not ready.
Anyhow contributions there are welcomed, and if you use it it could be included as an official data model.

**Comment by albertoabellagarcia** [comment]
We are assessing this data model for node that is able to cope with this requirement. 
See the link https://github.com/smart-data-models/incubated/tree/master/Node

**Comment by albertoabellagarcia** [comment]
no answer for further needs  in a month
