### ISSUE TITLE
Attributes controlledProperty and category are no longer defined

### ISSUE THREAD

**Issue by michzimny** [smart-data-models/dataModel.Device#9]
Hello,
recent commits 386e02973408a4d241cfa69e18231a8a49f5c4a9 and 8078d0336d6879db23231db7b8d4b5f66567326e made substantial edits to this data model.

One of the outcomes is that attributes `controlledProperty` and `category` are no longer defined. I suggest to restore the deleted information.

**Comment by albertoabellagarcia** [comment]
I am afraid that you did not notice of the line 
"$ref": "https://smart-data-models.github.io/dataModel.Device/device-schema.json#/definitions/Device-Commons"
where these properties remained untouched.
what is true is that they were missing the description from the [shared device schema](https://smart-data-models.github.io/dataModel.Device/device-schema.json) and consequently they did not appear in the spec. 
We have already documented them, and when we launch the updating of the specs it will be corrected. 
So thank you for noticing that. the spec will be updated soon to reflect them.

**Comment by albertoabellagarcia** [comment]
updated specification

**Comment by michzimny** [comment]
Thank you. My point was about https://github.com/smart-data-models/dataModel.Device/blob/master/Device/doc/spec.md. Sorry for not being clear enough.

However, there are still some problems with `category`, so I think this issue should be reopened:

1. In [DeviceModel/doc/spec.md](https://github.com/smart-data-models/dataModel.Device/blob/master/DeviceModel/doc/spec.md), `category` is not defined.
2. In [Device/doc/spec.md](https://github.com/smart-data-models/dataModel.Device/blob/master/Device/doc/spec.md), `category` is bad formatted.

Re 1:
It was well described before the changes in December:

> -   `category` : Device's category(ies).
    -   Attribute type: Property. List of [Text](https://schema.org/Text)
    -   Allowed values, one of the following or any other meaningful to the
        application:
    -   `sensor` : A device that detects and responds to events or changes in
        the physical environment such as light, motion, or temperature changes.
        [https://w3id.org/saref#Sensor](https://w3id.org/saref#Sensor).
    -   `actuator` : A device responsible for moving or controlling a mechanism
        or system. [https://w3id.org/saref#Actuator](https://w3id.org/saref#Actuator).
    - (...)

Re2 :

The current state:

> - `category`: A device that detects and responds to events or changes in the physical environment such as light, motion, or temperature changes. https://w3id.org/saref#Sensor. actuator : A device responsible for moving or controlling a mechanism or system. https://w3id.org/saref#Actuator. Meter : A device built to accurately detect and display a quantity in a form readable by a human being. Partially defined by SAREF. HVAC : Heating, Ventilation and Air Conditioning (HVAC) device that provides indoor environmental comfort. https://w3id.org/saref#HVAC. Network : A device used to connect other devices in a network, such as hub, switch or router in a LAN or Sensor network. (https://w3id.org/saref#Network.Multimedia : A device designed to display, store, record or play multimedia content such as audio, images, animation, video. Enum:'actuator, beacon, endgun, HVAC, implement, irrSection, irrSystem, meter, multimedia, network, sensor'  

For instance, it is not clear what is the first part about ("A device that detects..."). Perhaps, word "sensor" is missing in the beginning. Attribute type is missing. It says 'Meter', but the correct value is 'meter'. A parenthesis is open but not closed. etc.

**Comment by michzimny** [comment]
Forgive me but the problem is that we were referring to this documentation in our project, and since those changes, it's harder to read and to understand by newcomers.
